# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ivan Chromjak
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Ivan, a full stack web developer, designer and the author of this blog.
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:title/
url: "https://ivanchromjak.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: ichromjak

logo: "/assets/img/logo-dark.svg"
social:
  name: Ben Balter
  links:
    - https://twitter.com/ichromjak
    - https://www.linkedin.com/in/ivan-chromjak-2946b043/
    - https://github.com/chromjak

twitter_username: ichromjak
github_username:  chromjak
# instagram_accesstoken: 1045245980.ba4c844.e4e85ffbd253421ebf463634a9245454
# google_analytics:
footer_text: Designed and built with all the love in the world by <a href="https://twitter.com/mdo" target="_blank">@mdo</a> and <a href="https://twitter.com/fat" target="_blank">@fat</a>. Maintained by the <a href="https://github.com/orgs/twbs/people">core team</a> with the help of <a href="https://github.com/twbs/bootstrap/graphs/contributors">our contributors</a>.
# paginate: 2

# Build settings
markdown: kramdown
highlighter: rouge

# theme: minima
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
exclude:
  - Gemfile
  - Gemfile.lock
